# Generated by Django 2.2.13 on 2020-09-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecdetails',
            name='comment_sentiments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonecdetails',
            name='comment_page_id',
            field=models.IntegerField(default=0),
        ),
    ]
